[package]
name = "tic_tac_toe_rust"
version = "0.2.1"
edition = "2021"
description = "A simple tic tac toe game with a minimax ai"
repository = "https://github.com/jungersa/tic_tac_toe_rust"
license = "MIT"

[dependencies]
